import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisWrapper from "./Components/LenisWrapper";
import AppLayout from "./layouts/AppLayout";
import { BottomNav } from "./Components/BottomNav";

// Import the new application wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inzeedo - Mobile POS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisWrapper>           
            {children}
      <BottomNav />
        </LenisWrapper>
      </body>
    </html>
  );
}